// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Myweb.Ef_model
{
    public partial class CoinHistory
    {
        public int Id { get; set; }
        public int? Operation { get; set; }
        public decimal? Amount { get; set; }
        public DateTime? TranDate { get; set; }
        public int? UserId { get; set; }

        public virtual User User { get; set; }
    }
}