// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Myweb.Ef_model
{
    public partial class Gaccount
    {
        public Gaccount()
        {
            GaccountGame = new HashSet<GaccountGame>();
            GaccountTreasure = new HashSet<GaccountTreasure>();
        }

        public int Id { get; set; }
        public int? UserId { get; set; }

        public virtual User User { get; set; }
        public virtual ICollection<GaccountGame> GaccountGame { get; set; }
        public virtual ICollection<GaccountTreasure> GaccountTreasure { get; set; }
    }
}