// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Myweb.Ef_model
{
    public partial class GaccountTreasure
    {
        public int Id { get; set; }
        public int? GaccountId { get; set; }
        public int? TreasureId { get; set; }

        public virtual Gaccount Gaccount { get; set; }
        public virtual Treasure Treasure { get; set; }
    }
}