// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Myweb.Ef_model
{
    public partial class Game
    {
        public Game()
        {
            GaccountGame = new HashSet<GaccountGame>();
            Treasure = new HashSet<Treasure>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<GaccountGame> GaccountGame { get; set; }
        public virtual ICollection<Treasure> Treasure { get; set; }
    }
}