// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Myweb.Ef_model
{
    public partial class Treasure
    {
        public Treasure()
        {
            GaccountTreasure = new HashSet<GaccountTreasure>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int? GameId { get; set; }

        public virtual Game Game { get; set; }
        public virtual ICollection<GaccountTreasure> GaccountTreasure { get; set; }
    }
}